name: Demo Deploy
on: [push]

jobs:
  deploy-local-instance:
    runs-on: macos-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: "20"
        - name: Setup Pages
          uses: actions/configure-pages@v5
          with:
            static_site_generator: next
        - name: Install dependencies
          run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
        - name: Build with Next.js
          run: ${{ steps.detect-package-manager.outputs.runner }} next build
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: ./out